# .github/workflows/deploy.yaml
name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Or your desired Node.js version

      - name: Install dependencies
        run: npm install # Or yarn install, pnpm install

      - name: Build Next.js app
        run: npm run build # This will generate the 'out' directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          # Optional: If you need to bypass Jekyll for dotfiles like .nojekyll
          # cname: your-custom-domain.com # If using a custom domain
